import * as p from '@clack/prompts';
import pc from 'picocolors';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import { distillPersona } from './module1_distill.js';
import { tunePersona } from './module2_tune.js';
import { collectEconomy } from './module3_economy.js';
import { collectMemoryConfig } from './module4_memory.js';
import type { AgentConfig } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Output path: packages/worker/generated/
const GENERATED_DIR = path.resolve(__dirname, '../../worker/generated');

async function main() {
  console.clear();

  p.intro(pc.bgMagenta(pc.white(' 🔮 Twitter Agent Wizard ')));

  p.log.message(pc.dim('This wizard will help you create a custom AI digital avatar for X (Twitter).'));
  p.log.message(pc.dim('It will generate config.json and persona.skill in packages/worker/generated/'));
  p.log.message('');

  // ── Module 1: Distill ──────────────────────────────────────────────────────
  p.log.step(pc.cyan('Module 1 — Distilling Persona from Source Accounts'));
  const { draftSkill, sourceAccounts, geminiApiKey, xBearerToken, agentName, agentHandle } =
    await distillPersona();

  // ── Module 2: Tune (RLHF) ─────────────────────────────────────────────────
  p.log.step(pc.cyan('Module 2 — RLHF Tuning Loop'));
  const { finalSkill } = await tunePersona({ draftSkill, geminiApiKey });

  // ── Module 3: Economy & Probability ───────────────────────────────────────
  p.log.step(pc.cyan('Module 3 — Economy & Probability System'));
  const economyConfig = await collectEconomy();

  // ── Module 4: Memory Whitelist ─────────────────────────────────────────────
  p.log.step(pc.cyan('Module 4 — Memory Shaping & Evolution Config'));
  const memoryConfig = await collectMemoryConfig();

  // ── Assemble final AgentConfig ─────────────────────────────────────────────
  const config: AgentConfig = {
    agentName,
    agentHandle,
    sourceAccounts,
    defaultReplyProbability: economyConfig.defaultReplyProbability,
    defaultLikeProbability: economyConfig.defaultLikeProbability,
    vipList: economyConfig.vipList,
    memoryWhitelist: memoryConfig.memoryWhitelist,
    enableNightlyEvolution: memoryConfig.enableNightlyEvolution,
    spontaneousCooldownDays: economyConfig.spontaneousCooldownDays,
    cronSchedules: economyConfig.cronSchedules,
  };

  // ── Write output files ─────────────────────────────────────────────────────
  mkdirSync(GENERATED_DIR, { recursive: true });

  const configPath = path.join(GENERATED_DIR, 'config.json');
  const skillPath = path.join(GENERATED_DIR, 'persona.skill');

  writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf8');
  writeFileSync(skillPath, finalSkill, 'utf8');

  // ── Write .dev.vars for worker ─────────────────────────────────────────────
  const devVarsPath = path.resolve(__dirname, '../../worker/.dev.vars');
  const devVarsContent = [
    `# Generated by pnpm wizard — fill in the secrets below`,
    `GEMINI_API_KEY=${geminiApiKey}`,
    `X_CLIENT_ID=FILL_IN`,
    `X_CLIENT_SECRET=FILL_IN`,
    `X_REFRESH_TOKEN=FILL_IN`,
    `ADMIN_SECRET=FILL_IN_A_RANDOM_SECRET`,
  ].join('\n');
  writeFileSync(devVarsPath, devVarsContent, 'utf8');

  p.log.success(pc.green('✅ Files generated successfully!'));
  p.log.message('');
  p.log.message(pc.bold('📁 Generated files:'));
  p.log.message(`   ${pc.cyan(configPath)}`);
  p.log.message(`   ${pc.cyan(skillPath)}`);
  p.log.message(`   ${pc.cyan(devVarsPath)} ${pc.dim('(fill in X OAuth credentials)')}`);

  p.log.message('');
  p.log.message(pc.bold('🚀 Next steps to deploy:'));
  p.log.message('');
  p.log.message(pc.dim('1. Create KV namespace and get the ID:'));
  p.log.message(`   ${pc.yellow('cd packages/worker')}`);
  p.log.message(`   ${pc.yellow('npx wrangler kv namespace create AGENT_STATE')}`);
  p.log.message(pc.dim('   → Copy the ID and paste it into wrangler.toml (replace PLACEHOLDER_REPLACE_WITH_YOUR_KV_ID)'));
  p.log.message('');
  p.log.message(pc.dim('2. Seed initial persona.skill into KV:'));
  p.log.message(`   ${pc.yellow(`npx wrangler kv key put --binding=AGENT_STATE agent:skill "$(cat generated/persona.skill)"`)}`);
  p.log.message('');
  p.log.message(pc.dim('3. Set Worker secrets (X OAuth credentials):'));
  p.log.message(`   ${pc.yellow('npx wrangler secret put X_CLIENT_ID')}`);
  p.log.message(`   ${pc.yellow('npx wrangler secret put X_CLIENT_SECRET')}`);
  p.log.message(`   ${pc.yellow('npx wrangler secret put X_REFRESH_TOKEN')}`);
  p.log.message(`   ${pc.yellow('npx wrangler secret put GEMINI_API_KEY')}`);
  p.log.message(`   ${pc.yellow('npx wrangler secret put ADMIN_SECRET')}`);
  p.log.message('');
  p.log.message(pc.dim('4. Deploy:'));
  p.log.message(`   ${pc.yellow('npx wrangler deploy')}`);
  p.log.message(pc.dim('   Or from repo root: ') + pc.yellow('pnpm deploy'));

  p.outro(pc.bgGreen(pc.black(' Agent configuration complete! 🎉 ')));
}

main().catch(err => {
  console.error(pc.red('Fatal error:'), err);
  process.exit(1);
});
