// ─── Agent Configuration (generated by wizard, bundled at build time) ─────────

export interface VipEntry {
  /** X username (without @) */
  username: string;
  /** 0–1. Overrides defaultReplyProbability when this user is the author. */
  replyProbability: number;
  /** 0–1. Overrides defaultLikeProbability for timeline interactions. */
  likeProbability: number;
  /** Short human-readable label, e.g. "主人宠溺模式" | "同行锐评模式" */
  persona?: string;
  /** Full LLM system-prompt override injected when this user is encountered. */
  personaInstruction?: string;
}

export interface CronSchedules {
  /** Mention polling, e.g. "* * * * *" */
  mentionPoll: string;
  /** Spontaneous tweet trigger, e.g. "30 12 * * *" */
  spontaneous: string;
  /** Timeline engagement sweep, e.g. "0 * * * *" */
  timelineEngagement: string;
  /** Memory consolidation, e.g. "0 star/6 * * *" where star=every N hours */
  memoryRefresh: string;
  /** Nightly evolution, e.g. "0 3 * * *" */
  nightlyEvolution: string;
}

export interface AgentConfig {
  /** Display name of the agent, used in the admin dashboard title */
  agentName: string;
  /** X @handle the agent operates as (for display only; actual auth is via tokens) */
  agentHandle: string;
  /** X accounts whose tweets were used to distill the persona (used for debug endpoint) */
  sourceAccounts: string[];
  /** 0–1 probability that the agent replies to a non-VIP mention (rest → <skip>) */
  defaultReplyProbability: number;
  /** 0–1 probability that the agent likes a non-VIP timeline tweet */
  defaultLikeProbability: number;
  /** Special persona rules per user */
  vipList: VipEntry[];
  /**
   * Which users' interactions are absorbed into long-term memory.
   * 'all' = everyone, or array of specific usernames.
   */
  memoryWhitelist: string[] | 'all';
  /** Whether to run the nightly personality evolution cycle */
  enableNightlyEvolution: boolean;
  /** Minimum days between spontaneous tweets */
  spontaneousCooldownDays: number;
  /** Cron schedule strings — must match entries in wrangler.toml */
  cronSchedules: CronSchedules;
}

// ─── Environment bindings (Cloudflare Worker) ─────────────────────────────────

export interface Env {
  /** KV namespace for all persistent agent state */
  AGENT_STATE: KVNamespace;
  /** X App OAuth 2.0 Client ID */
  X_CLIENT_ID: string;
  /** X App OAuth 2.0 Client Secret */
  X_CLIENT_SECRET: string;
  /** Long-lived refresh token obtained from the one-time auth flow */
  X_REFRESH_TOKEN: string;
  /** Google Gemini API key */
  GEMINI_API_KEY: string;
  /** Secret value for protected admin endpoints (header or ?secret= param) */
  ADMIN_SECRET: string;
}

// ─── X API types ───────────────────────────────────────────────────────────────

export interface XTokenResponse {
  access_token: string;
  refresh_token?: string;
  expires_in: number;
  token_type: string;
  scope: string;
}

export interface XMedia {
  media_key: string;
  type: 'photo' | 'video' | 'animated_gif';
  url?: string;
  preview_image_url?: string;
}

export interface XTweet {
  id: string;
  text: string;
  author_id?: string;
  created_at?: string;
  conversation_id?: string;
  edit_history_tweet_ids?: string[];
  referenced_tweets?: Array<{
    type: 'replied_to' | 'quoted' | 'retweeted';
    id: string;
  }>;
  attachments?: {
    media_keys?: string[];
  };
}

export interface XMentionsResponse {
  data?: XTweet[];
  meta?: {
    newest_id?: string;
    oldest_id?: string;
    result_count?: number;
    next_token?: string;
  };
  includes?: {
    tweets?: XTweet[];
    media?: XMedia[];
    users?: Array<{ id: string; name: string; username: string }>;
  };
}

export interface XTweetLookupResponse {
  data?: XTweet;
  includes?: {
    tweets?: XTweet[];
    media?: XMedia[];
    users?: Array<{ id: string; name: string; username: string }>;
  };
}

export interface TweetPayload {
  text: string;
  reply?: { in_reply_to_tweet_id: string };
  media?: { media_ids: string[] };
}

export interface TweetResponse {
  data: {
    id: string;
    text: string;
  };
}

// ─── Agent conversation context ────────────────────────────────────────────────

export interface ConversationTurn {
  role: 'user' | 'agent';
  text: string;
  authorId?: string | undefined;
  authorUsername?: string | undefined;
  mediaNote?: string | undefined;
}

// ─── KV-persisted state ────────────────────────────────────────────────────────

export interface StoredTokens {
  accessToken: string;
  refreshToken: string;
  /** Unix timestamp (ms) when the access token expires */
  expiresAt: number;
}

export interface InteractionMemory {
  id: string;
  type: 'mention' | 'reply';
  authorUsername: string;
  text: string;
  createdAt: string;
}


export interface ActivityLog {
  id: string;
  type: 'view' | 'like' | 'reply' | 'post' | 'follow';
  targetUsername?: string | undefined;
  content: string;
  timestamp: number;
}
