// ─── Agent Configuration (generated by wizard, bundled at build time) ─────────

export interface VipEntry {
  /** X username (without @) */
  username: string;
  /** 0–1. Overrides defaultReplyProbability when this user is the author. */
  replyProbability: number;
  /** 0–1. Overrides defaultLikeProbability for timeline interactions. */
  likeProbability: number;
  /** Short human-readable label, e.g. "主人宠溺模式" | "同行锐评模式" */
  persona?: string;
  /** Full LLM system-prompt override injected when this user is encountered. */
  personaInstruction?: string;
}

export interface CronSchedules {
  /** Mention polling, e.g. "* * * * *" */
  mentionPoll: string;
  /** Spontaneous tweet trigger, e.g. "30 12 * * *" */
  spontaneous: string;
  /** Timeline engagement sweep, e.g. "0 * * * *" */
  timelineEngagement: string;
  /** Memory consolidation, e.g. "0 star/6 * * *" where star=every N hours */
  memoryRefresh: string;
  /** Nightly evolution, e.g. "0 3 * * *" */
  nightlyEvolution: string;
}

export interface AgentDbRecord {
  id: string;
  owner_id: string;
  agent_name: string;
  agent_handle: string;
  source_accounts: string[]; // parsed
  gemini_model: string;
  gemini_api_key: string;
  refresh_token: string;
  access_token: string | null;
  token_expires_at: number;
  skill_text: string;
  reply_pct: number;
  like_pct: number;
  cooldown_days: number;
  auto_evo: boolean;
  vip_list: VipEntry[]; // parsed
  mem_whitelist: string[] | 'all'; // parsed
  pro_expires_at: number;
  created_at: number;
  status: string;
}

// ─── Environment bindings (Cloudflare Worker) ─────────────────────────────────

export interface Env {
  /** Database for all configurations */
  DB: D1Database;
  /** KV namespace for all persistent agent state */
  AGENT_STATE: KVNamespace;
  /** X App OAuth 2.0 Client ID */
  X_CLIENT_ID: string;
  /** X App OAuth 2.0 Client Secret */
  X_CLIENT_SECRET: string;
  /** Secret value for protected admin endpoints (header or ?secret= param) */
  ADMIN_SECRET: string;
  /** Gemini API Key (已废弃，由 CF AI Gateway Token 接管) */
  GEMINI_API_KEY?: string;
  /** Default Gemini Model Name, e.g. gemini-2.5-pro-preview-03-25 */
  GEMINI_MODEL?: string;
  /** Cloudflare Account ID (for AI Gateway) */
  CF_ACCOUNT_ID: string;
  /** Cloudflare AI Gateway Name */
  CF_GATEWAY_NAME: string;
  /** Cloudflare AI Gateway Token (generated in the Gateway dashboard) */
  CF_AIG_TOKEN: string;
  /** Local dev only: override origin (e.g. http://localhost:8787) to bypass Wrangler domain rewriting */
  LOCAL_ORIGIN?: string;
  /** Ko-Fi Webhook verification token (set via wrangler secret put KO_FI_VERIFICATION_TOKEN) */
  KO_FI_VERIFICATION_TOKEN?: string;
  /** Minimum donation amount to generate a license key, e.g. "9" (set in wrangler.toml vars) */
  KO_FI_MINIMUM_AMOUNT?: string;
}

// ─── X API types ───────────────────────────────────────────────────────────────

export interface XTokenResponse {
  access_token: string;
  refresh_token?: string;
  expires_in: number;
  token_type: string;
  scope: string;
}

export interface XMedia {
  media_key: string;
  type: 'photo' | 'video' | 'animated_gif';
  url?: string;
  preview_image_url?: string;
}

export interface XTweet {
  id: string;
  text: string;
  author_id?: string;
  created_at?: string;
  conversation_id?: string;
  edit_history_tweet_ids?: string[];
  referenced_tweets?: Array<{
    type: 'replied_to' | 'quoted' | 'retweeted';
    id: string;
  }>;
  attachments?: {
    media_keys?: string[];
  };
}

export interface XMentionsResponse {
  data?: XTweet[];
  meta?: {
    newest_id?: string;
    oldest_id?: string;
    result_count?: number;
    next_token?: string;
  };
  includes?: {
    tweets?: XTweet[];
    media?: XMedia[];
    users?: Array<{ id: string; name: string; username: string }>;
  };
}

export interface XTweetLookupResponse {
  data?: XTweet;
  includes?: {
    tweets?: XTweet[];
    media?: XMedia[];
    users?: Array<{ id: string; name: string; username: string }>;
  };
}

export interface TweetPayload {
  text: string;
  reply?: { in_reply_to_tweet_id: string };
  media?: { media_ids: string[] };
}

export interface TweetResponse {
  data: {
    id: string;
    text: string;
  };
}

// ─── Agent conversation context ────────────────────────────────────────────────

export interface ConversationTurn {
  role: 'user' | 'agent';
  text: string;
  authorId?: string | undefined;
  authorUsername?: string | undefined;
  mediaNote?: string | undefined;
}

// ─── KV-persisted state ────────────────────────────────────────────────────────

export interface StoredTokens {
  accessToken: string;
  refreshToken: string;
  /** Unix timestamp (ms) when the access token expires */
  expiresAt: number;
}

export interface InteractionMemory {
  id: string;
  type: 'mention' | 'reply';
  authorUsername: string;
  text: string;
  createdAt: string;
}


export interface ActivityLog {
  id: string;
  type: 'view' | 'like' | 'reply' | 'post' | 'follow';
  targetUsername?: string | undefined;
  content: string;
  timestamp: number;
}
